# Generated by Django 5.1.1 on 2025-01-08 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="inquiriedId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.buyer"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="buyerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.buyer"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="sellerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.seller"
            ),
        ),
    ]
