# Generated by Django 5.1.5 on 2025-01-26 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_buyer_seller_alter_inquiry_inquiriedid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 26)),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 26)),
        ),
    ]
