# Generated by Django 5.1.5 on 2025-01-27 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0003_alter_inquiry_date_alter_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 27)),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 27)),
        ),
    ]
