# Generated by Django 5.1.5 on 2025-01-28 15:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0004_alter_inquiry_date_alter_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="mediatorId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="App1.mediator",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 28)),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 1, 28)),
        ),
    ]
